# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreocorrencia', '0006_auto_20170818_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posteres',
            new_name='Poster',
        ),
    ]
