# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreocorrencia', '0009_delete_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='texto1',
            field=models.TextField(max_length=1000, null=True, verbose_name='Primeiro Parágrafo'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='texto2',
            field=models.TextField(max_length=1000, null=True, verbose_name='Segundo Parágrafo'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='texto3',
            field=models.TextField(max_length=1000, null=True, verbose_name='Terceiro Parágrafo'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='texto4',
            field=models.TextField(max_length=1000, null=True, verbose_name='Quarto Parágrafo'),
        ),
    ]
