# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreocorrencia', '0010_auto_20170818_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster_polit',
            name='texto',
        ),
        migrations.AddField(
            model_name='poster_polit',
            name='texto1',
            field=models.TextField(max_length=1000, null=True, verbose_name='Primeiro Parágrafo'),
        ),
        migrations.AddField(
            model_name='poster_polit',
            name='texto2',
            field=models.TextField(max_length=1000, null=True, verbose_name='Segundo Parágrafo'),
        ),
        migrations.AddField(
            model_name='poster_polit',
            name='texto3',
            field=models.TextField(max_length=1000, null=True, verbose_name='Terceiro Parágrafo'),
        ),
        migrations.AddField(
            model_name='poster_polit',
            name='texto4',
            field=models.TextField(max_length=1000, null=True, verbose_name='Quarto Parágrafo'),
        ),
    ]
