# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:12
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreocorrencia', '0011_auto_20170819_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fonte', models.CharField(max_length=200)),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
                ('texto', models.TextField(max_length=1000, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
            ],
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'ordering': ('-data_publicacao',)},
        ),
    ]
