# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreocorrencia', '0012_auto_20170824_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='texto2',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='texto3',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='texto4',
        ),
        migrations.AlterField(
            model_name='classificado',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
