# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreocorrencia', '0015_auto_20170825_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posteres',
            new_name='Poster',
        ),
    ]
