# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreocorrencia', '0016_auto_20170825_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster_polit',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Poster_polit',
        ),
    ]
